### ISSUE TITLE
可以提供一下训练的代码吗

### ISSUE THREAD

**Issue by ddzxlining** [ksnzh/ImageSmoothing.pytorch#1]
你好，我按照您的扩展自己写了训练的代码，但是不work。希望您能提供一下训练代码

**Comment by hdmjdp** [comment]
作者给的模型效果还行，你训练代码可以发下一起讨论下，看下为什么不 work，我也打算写 还没写，而且我准备写 cpu 版本
![WechatIMG1](https://user-images.githubusercontent.com/26831425/70865986-c0504000-1f9e-11ea-98a3-c78acfd84481.jpeg)

**Comment by hdmjdp** [comment]
![图片](https://user-images.githubusercontent.com/26831425/70865968-82ebb280-1f9e-11ea-8750-f3e78d2ae4c9.png)

**Comment by hypercost** [comment]
凭记忆大概说几点pyotch复现需要注意的点：
1）训练数据，弱监督的，需要提供原图像和对应边沿图像（用于告诉smoothloss哪些需要保边），我使用的是VOC数据集和对应的HED提取的edge
2）损失函数，每个任务有不同设置，按原论文去写https://github.com/fqnchina/ImageSmoothing/blob/master/train_stylization.lua#L148

另外，虽然是我做的，但我手上我没有训练代码，也没时间重新去写，能确保的是给的训练好的模型的确是pytorch训练的，上面的朋友也给了可视结果。

**Comment by hdmjdp** [comment]
> 凭记忆大概说几点pyotch复现需要注意的点：
> 1）训练数据，弱监督的，需要提供原图像和对应边沿图像（用于告诉smoothloss哪些需要保边），我使用的是VOC数据集和对应的HED提取的edge
> 2）损失函数，每个任务有不同设置，按原论文去写https://github.com/fqnchina/ImageSmoothing/blob/master/train_stylization.lua#L148
> 
> 另外，虽然是我做的，但我手上我没有训练代码，也没时间重新去写，能确保的是给的训练好的模型的确是pytorch训练的，上面的朋友也给了可视结果。

作者你好， 你的训练图的边缘图不是按照论文作者说的用的run_edgedetector.lua 提取的，而是用的HED是吗，我打算重写python版本的run_edgedetector.lua。不知道这种效果怎么样，另外可否告知用的HED的开源版本，HED貌似是神经网络的提取边缘算法，与作者给的方法差异应该蛮大的吧，有对比图吗

**Comment by hdmjdp** [comment]
@ksnzh https://github.com/fqnchina/ImageSmoothing/blob/11a8718310f0d64ee2a7140ec87300eb33f719e0/train_stylization.lua#L272 还有个疑问，这个地方为啥还要再跑一次边缘检测，不是很明白这是什么操作，本身边缘图作为label在训练前就已经提好了，训练过程中输出的结果是会计算一次边缘，但是在https://github.com/fqnchina/ImageSmoothing/blob/11a8718310f0d64ee2a7140ec87300eb33f719e0/train_stylization.lua#L142已经计算了吧，还望指导下

**Comment by hypercost** [comment]
loss计算中虽然名字上叫edge compute，实际上是按作者给的公式算的中间像素对于邻域的响应，比如说sobel梯度这种；而需要提前算好的edge是作为mask，告诉smoothloss哪些地方重要
2019年12月16日 +0800 PM2:14 hdmjdp <notifications@github.com>，写道：

**Comment by hdmjdp** [comment]
@ksnzh 感谢，你说的第一个问题是这个吗 label_all[{{},{4},{},{}}] = model_computeEdge:forward(input)吧

**Comment by luckyboy101** [comment]
> 作者给的模型效果还行，你训练代码可以发下一起讨论下，看下为什么不 work，我也打算写 还没写，而且我准备写 cpu 版本
> ![WechatIMG1](https://user-images.githubusercontent.com/26831425/70865986-c0504000-1f9e-11ea-98a3-c78acfd84481.jpeg)

能分享一下训练代码？我训练不出结果来。
